/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <assert.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>
#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
#include <android/log.h>

using namespace cv;
using namespace std;
/* Header for class com_example_sergeygorun_opencvhello_OpenCVNative */

#ifndef _Included_com_example_sergeygorun_opencvhello_OpenCVNative
#define _Included_com_example_sergeygorun_opencvhello_OpenCVNative
#ifdef __cplusplus
extern "C" {
#endif
Rect* artHaarDetection(Mat&);
void detectContours(Mat&, Rect);

/*
 * Class:     com_example_sergeygorun_opencvhello_OpenCVNative
 * Method:    convertGray
 * Signature: (JJ)I
 */
JNIEXPORT jboolean JNICALL Java_com_example_sergeygorun_opencvhello_OpenCVNative_artDetection
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
